### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by IronDemiGod** [danjperron/PicoAudioPWM#6]
I am trying to run the `TestwavePlayer.py` script included with this
i am getting this error:

```
Traceback (most recent call last):
  File "<stdin>", line 71, in <module>
  File "/lib/wavePlayer.py", line 164, in __init__
  File "/lib/myPWM.py", line 8, in __init__
ValueError: invalid syntax for integer with base 10
```

Am i doing something wrong?
Running this on a Raspberry Pi Pico with MicroPython

**Comment by danjperron** [comment]
Hi IronDemiGod. 

You that demi means half in french. so you are IronHalfGod. ;-)

It will take some timed before I could check if the new micropython change something to run this code.

In the mean time could your add a print to check what self.id is

ex:

class myPWM(PWM):
 def __init__(self,pin,divider=8,top=255):
 print("pin :",pin)
 self.id = int(str(pin)[4:-1].split(',')[0])
 print("id :",self.id)
 self.A_B = self.id & 1
 print("A_B :",self.A_B)
 self.channel = self.id >> 1

 print("channel", self.channel)



self.id should be integer and looks like it's not.

regards Daniel

**Comment by IronDemiGod** [comment]
Hi Daniel,

I replaced the code with what you provided, and now it is returning a different error

```
Traceback (most recent call last):
  File "<stdin>", line 43
IndentationError: unindent doesn't match any outer indent level
```

**Comment by IronDemiGod** [comment]
Hi Daniel,

**Comment by IronDemiGod** [comment]
I replaced it with the code you provided, and self.id() does not return an integer, but returns a string
Full output:

```
pin : Pin(GPIO15, mode=ALT, pull=PULL_DOWN, alt=31)
Traceback (most recent call last):
  File "<stdin>", line 58, in <module>
  File "<stdin>", line 7, in __init__
ValueError: invalid syntax for integer with base 10
```

Here is how the code looks like now:

```
class myPWM(PWM):
    def __init__(self, pin, divider=8, top=255):
        print("pin :",pin)
        self.id = int(str(pin)[4:-1].split(',')[0])
        print("id :",self.id)
        self.A_B = self.id & 1
        print("A_B :",self.A_B)
        self.channel = self.id >> 1
        print("channel", self.channel)
        self.divider = divider
        self.top = top
```

**Comment by danjperron** [comment]
ok pin return pin : 

Pin(GPIO15, mode=ALT, pull=PULL_DOWN, alt=31)

on old micropython it wasn't returning GPIO15 but 15 only. 

To fix it , replace the line with
self.id = int(str(pin)[8:-1].split(',')[0])
The command is to extract which GPIO is . Since it returns GPIO15 instead of 15 you need to start  the string at position 7 or 8 instead of 4 (first position is 0)

Please check if  print(str(pin)[8:-1].split(',')[0]) return  the string 15 only .


since the split command use the coma the (-1) parameter return the rest of the string  which ends before the coma,

N.B. I didn't check it but this is what I think it is.

Best regards,
 Daniel

**Comment by IronDemiGod** [comment]
I did this and now the code works perfectly
self.id() returns 2 (2 is the pin intended)

```
pin : Pin(GPIO2, mode=ALT, pull=PULL_DOWN, alt=PWM)
id : 2
A_B : 0
channel 1
```

Thank you so much for the help!
